spring:
  datasource:
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:3333}
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:survey}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Paris
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    generate-ddl: true

  cloud:
    consul:
      host: ${CONSUL_HOST:consul}
      port: ${CONSUL_PORT:8500}
      config:
        enabled: true
        profile-separator: "-"
        format: yaml
        fail-fast: false
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: false
