package com.medical.appointment.enums;

public enum DoctorSpecialty {


    GENERAL_PRACTITIONER,
    INTERNAL_MEDICINE,
    CARDIOLOGY,
    DERMATOLOGY,
    PEDIATRICS,
    GYNECOLOGY,
    OBSTETRICS,
    NEUROLOGY,
    PSYCHIATRY,
    ORTHOPEDICS,
    OPHTHALMOLOGY,
    OTOLARYNGOLOGY,
    UROLOGY,
    ONCOLOGY,
    RADIOLOGY,
    ANESTHESIOLOGY,
    EMERGENCY_MEDICINE,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    PULMONOLOGY
}
