spring:
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
      port: 8500
      host: localhost

    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:4200"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowed-headers:
                  - "*"
            add-to-simple-url-handler-mapping: true
          routes:
            - id: auth
              uri: lb://auth-8081
              predicates:
                - Path=/usr/**
              filters:
                - RewritePath=usr/(?<segment>.*),user/${segment}

            - id: appointment
              uri: lb://appointment-8082
              predicates:
                - Path=/ap/**
              filters:
                - RewritePath=ap/(?<segment>.*),appointment/${segment}

            - id: doctor
              uri: lb://appointment-8082
              predicates:
                - Path=/doc/**
              filters:
                - RewritePath=doc/(?<segment>.*),doctor/${segment}