server:
  port: 9000

spring:
  application:
    name: gateway-9000
  profiles:
    active: @spring.profile.active@

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location:  "classpath:keys/public_key.pem"
  config:
    import: "optional:consul:"